title: "Rajveer Kushwaha Portfolio"
description: "Cybersecurity Engineer Portfolio & Blog"
baseurl: ""  
url: "https://rajveerkushwaha.engineer"
plugins:
  - jekyll-feed
# _config.yml addition
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default-social.jpg  
