title: "Rajveer Kushwaha Portfolio"
description: "Cybersecurity Engineer Portfolio & Blog"
baseurl: ""  # leave empty if using root domain
url: "https://rajveerkushwaha.engineer"
theme: minima
plugins:
  - jekyll-feed
